apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myresiliency
  namespace: aspire-dapr-demo

spec:
  type: resiliency
  metadata:
    - name: app
      value: aspire-dapr-demo

  scopes:
    - alice
    - bob

  policy:
    retries:
      retryForever:
        policy: constant
        interval: 5s
        threshold: -1

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s
        threshold: 5

  targets:
    apps:
      - name: bob
        retryPolicy: retryForever
        circuitBreakerPolicy: simpleCB
